# frozen_string_literal: true
source 'https://rubygems.org'

gem 'chef', '~> 17.0'
gem 'chefspec', '~> 9.0'
gem 'rspec', '~> 3.10'
gem 'rspec-its', '~> 1.3'
gem 'fuubar', '~> 2.5'

group :test do
  # Asegura que el directorio raíz esté en el load path
  $LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '.'))
  $LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'spec'))
end