# Rakefile para ejecutar pruebas unitarias de Chef

require 'rspec/core/rake_task'

# Tarea por defecto para ejecutar todas las pruebas unitarias
desc 'Ejecutar todas las pruebas unitarias'
RSpec::Core::RakeTask.new(:spec) do |task|
  task.pattern = 'cookbooks/**/spec/**/*_spec.rb'
  task.rspec_opts = ['--color', '--format', 'Fuubar']
end

# Tareas individuales para cada cookbook
desc 'Ejecutar pruebas unitarias para el cookbook de Apache'
RSpec::Core::RakeTask.new('spec:apache') do |task|
  task.pattern = 'cookbooks/apache/spec/**/*_spec.rb'
  task.rspec_opts = ['--color', '--format', 'Fuubar']
end

desc 'Ejecutar pruebas unitarias para el cookbook de MySQL'
RSpec::Core::RakeTask.new('spec:mysql') do |task|
  task.pattern = 'cookbooks/mysql/spec/**/*_spec.rb'
  task.rspec_opts = ['--color', '--format', 'Fuubar']
end

desc 'Ejecutar pruebas unitarias para el cookbook de PHP'
RSpec::Core::RakeTask.new('spec:php') do |task|
  task.pattern = 'cookbooks/php/spec/**/*_spec.rb'
  task.rspec_opts = ['--color', '--format', 'Fuubar']
end

desc 'Ejecutar pruebas unitarias para el cookbook de WordPress'
RSpec::Core::RakeTask.new('spec:wordpress') do |task|
  task.pattern = 'cookbooks/wordpress/spec/**/*_spec.rb'
  task.rspec_opts = ['--color', '--format', 'Fuubar']
end

# Alias para conveniencia
task :test => :spec