require 'rspec/core/rake_task'

# Definir tarea para ejecutar pruebas unitarias de todos los cookbooks
RSpec::Core::RakeTask.new(:spec) do |task|
  task.pattern = 'cookbooks/*/spec/**/*_spec.rb'
  task.rspec_opts = ['--color', '--format Fuubar']
end

# Tarea para ejecutar pruebas de un cookbook específico
namespace :spec do
  %w[apache mysql php wordpress].each do |cookbook|
    RSpec::Core::RakeTask.new(cookbook.to_sym) do |task|
      task.pattern = "cookbooks/#{cookbook}/spec/**/*_spec.rb"
      task.rspec_opts = ['--color', '--format Fuubar']
    end
  end
end

# Tarea por defecto
task default: :spec